### ISSUE TITLE
Set Position

### ISSUE THREAD

**Issue by arkhan** [muffinmad/emacs-mini-frame#1]
Great job is great,

Only one query can put an option to choose the position of the minibuffer, in my case I would like it to be at the bottom.

Greetings.

**Comment by muffinmad** [comment]
Thanks!

Well, you have minibuffer at the bottom in vanilla Emacs, you don't need package for that ;)

There are `mini-frame-show-parameters` user option - alist of frame parameters for child frame. 

Try this parameters:
```elisp
(custom-set-variables
 '(mini-frame-show-parameters
   '((left . 0.5)
     (top . -100)
     (width . 1.0)
     (height . 1))))
```

See [position frame parameters](https://www.gnu.org/software/emacs/manual/html_node/elisp/Position-Parameters.html) for more info.

**Comment by tumashu** [comment]
maybe you can use posframe to simplify code

**Comment by muffinmad** [comment]
> maybe you can use posframe to simplify code

I don't see how posframe can be used. Frames created by posframe has following frame parameters:
```elisp
(no-accept-focus . t)
(minibuffer . nil)
```

But for minibuffer frame I need quite opposite.

Also I like flexibility of `top`, `left`, `width` and `height` standard frame parameters instead of poshandlers. Though window and point related poshandlers are great.

**Comment by clemera** [comment]
One can make use posframe position handlers for setting up frame display at point:

```elisp
(setq mini-frame-show-parameters
      (lambda ()
        (let* ((info
                `(:position-info ,(posn-at-point)
                  :x-pixel-offset 0
                  :y-pixel-offset 0
                  :font-height ,(posframe--get-font-height (point))
                  :parent-window ,(selected-window)
                  :parent-frame-width ,(frame-pixel-width)
                  :parent-frame-height ,(frame-pixel-height)
                  :header-line-height ,(window-header-line-height)
                  :tab-line-height ,(if (functionp 'window-tab-line-height)
                                        (window-tab-line-height)
                                      0)))
               (posn (posframe-poshandler-point-bottom-left-corner info))
               (left (car posn))
               (top (cdr posn)))
          `((left . ,left)
            (top . ,top)
            (width . 80)
            (height . 1)))))
```

**Comment by muffinmad** [comment]
@clemera Thanks!

IMO having some helper to create the `info` this code will perfectly fit the user's `init.el` ;)

**Comment by clemera** [comment]
@tumashu Maybe a helper to create the info needed by poshandlers could be added to posframe?

**Comment by muffinmad** [comment]
Or maybe calculation of the frame related point position can be added to Emacs itself. Something like `point-pos-in-frame`.

**Comment by clemera** [comment]
@muffinmad That would be ideal :) Though it would still be nice if posframe would also include a helper to create the needed info for its position functions.

**Comment by muffinmad** [comment]
> @muffinmad That would be ideal :)

Yeah.

In my other package child frame is placed at point and I think calculations are similar: https://github.com/muffinmad/emacs-completions-frame/blob/95e0845fdac5412a511ca15b12189ed9487a64a7/completions-frame.el#L112

Really complicated.

**Comment by clemera** [comment]
Nice, I did know about your other package but forgot about it :) Would you like to propose the calculation function for inclusion?

**Comment by muffinmad** [comment]
> Would you like to propose the calculation function for inclusion?

It may be worth it if posframe will also benefit from such function. Anyway feel free to beat me in it ;)

**Comment by tumashu** [comment]
@clemera  Not have at the moment,  it is in posframe-show.

**Comment by clemera** [comment]
@tumashu That is where I extracted it from, would be nice to have a function which creates the info so one can easuly use the position functions for other purposes :)

**Comment by tumashu** [comment]
@clemera like this? https://github.com/tumashu/posframe/pull/91
