### ISSUE TITLE
read-regexp vs read-string; isearch

### ISSUE THREAD

**Issue by podczeck** [muffinmad/emacs-mini-frame#15]
First, thanks for your nice contribution!

I have two issues with mini-frame-mode enabled:

(1) E.g., do "M-x apropos". Everything is fine up to this point. However, as soon as I then do "Ret", I am in the usual minibuffer, i.e. that which appears without  mini-frame-mode. But if, in apropos.el, I change the occurence of "read-string" into "read-regexp", I stay in the new frame, as expected.

(2) Doing "C-s" do invoke isearch, I come immediately in the usual minibuffer.

Konrad

**Comment by muffinmad** [comment]
> First, thanks for your nice contribution!

I'm glad you find it useful!

> (1) E.g., do "M-x apropos". Everything is fine up to this point. However, as soon as I then do "Ret", I am in the usual minibuffer, i.e. that which appears without mini-frame-mode. But if, in apropos.el, I change the occurence of "read-string" into "read-regexp", I stay in the new frame, as expected.

`read-string` doesn't use `read-from-minibuffer`. And the `mini-frame-read-from-minibuffer ` advice is intentionally removed from `read-string` in https://github.com/muffinmad/emacs-mini-frame/commit/30000e659b0ad2501591343b4818e5877783483b.

> (2) Doing "C-s" do invoke isearch, I come immediately in the usual minibuffer.

`isearch-forward` doesn't use `read-from-minibuffer` either. But `M-e` after `C-s` does ;)
