### ISSUE TITLE
Set Alpha.

### ISSUE THREAD

**Issue by templateK** [muffinmad/emacs-mini-frame#16]
First, Awesome pacakge. ❤️  

I tried set alpha value of the minibuffer frame by below code.

```elisp
(setq mini-frame-show-parameters '((alpha . (80 70)) (top . 20) (width . 0.6) (left . 0.5)))
```
and I see the value `(80 70)` by evaluate `(frame-parameter mini-frame-frame 'alpha)` 
but it has no effect.

**Comment by muffinmad** [comment]
> First, Awesome pacakge.

Thanks!

> and I see the value (80 70) by evaluate (frame-parameter mini-frame-frame 'alpha)
but it has no effect.

According to [docs](https://www.gnu.org/software/emacs/manual/html_node/elisp/Font-and-Color-Parameters.html#Font-and-Color-Parameters)
> The alpha frame parameter can also be a cons cell (active . inactive)

So please try `(alpha . (80 . 70))`.

**Comment by templateK** [comment]
I tried yours suggestion and it shows `(80 . 70)` and still has no effect.
When I run `(frame-parameter (selected-frame) 'alpha)` on my emacs main frame which successfully have changed the alpha value, I get `(80 70)`.

**Comment by muffinmad** [comment]
OK, then please specify your OS. And consider attach screenshots with active mini-frame and with inactive mini-frame.

**Comment by templateK** [comment]
OS: macOS Mojave
Emacs: GNU Emacs 27.0.90
When mini-frame-frame is shows for first time, it has no alpha and then re-activating the frame applies the value.

<details><summary>Screent Shots</summary>

first time activated
![first_active](https://user-images.githubusercontent.com/3207776/82223667-e74fdb00-995d-11ea-8013-dedea62ecada.png)

re-activated 
![re_active](https://user-images.githubusercontent.com/3207776/82223703-f5056080-995d-11ea-860e-fc93b8cd9aa3.png)

inactivated
![inactive](https://user-images.githubusercontent.com/3207776/82223736-03ec1300-995e-11ea-98f1-501d9f32ac1a.png)
</details>

**Comment by templateK** [comment]
Now I figured out. I was using window tiling manager and it was messing my emacs. 
The alpha setting works below code with no problem.
```elisp
(setq mini-frame-show-parameters '((alpha . (80 70)) ))
``` 
Sorry for the noise and again, thanks for the quick response and your hard work. 👍

**Comment by muffinmad** [comment]
Good to know!

Thanks again!

Closing this then.
