### ISSUE TITLE
Does not show full minibuffer with some Selectrum functions

### ISSUE THREAD

**Issue by gcv** [muffinmad/emacs-mini-frame#17]
Selectrum is a good candidate to pair with mini-frame-mode, but I found the following incompatibility: with mini-frame-mode turned on, some commands (like `switch-to-buffer`) do not show the expected candidate list. Other commands (`find-file`) have no problem.

To reproduce, get a sandbox Emacs environment and install Selectrum. Then install mini-frame-mode. Enable just Selectrum (`(selectrum-mode 1)`). Play around with it, note how `find-file` and `switch-to-buffer` show candidate lists right away. Now turn on mini-frame-mode (`(mini-frame-mode 1)`). Note that `find-file` shows a candidate list, just as expected, but `switch-to-buffer` only shows one when you start typing.

Not sure what's going on here, but it looks like, under some conditions, mini-frame-mode does not show the full minibuffer.

**Comment by muffinmad** [comment]
Looks like `selectrum-read-file-name` is the only function that shows candidate list initially.
This simple snippet doesn't show candidate list:
```elisp
(completing-read "foo: " (list "bar1" "bar2" "bar3"))
```

**Comment by gcv** [comment]
It shows the full candidate list when mini-frame-mode is off. I can ping the selectrum guys about it, but since it works as expected in their normal configuration, I'm sure they'll point back to mini-frame as the culprit...

**Comment by muffinmad** [comment]
> I can ping the selectrum guys about it

Already done it. See https://github.com/raxod502/selectrum/issues/169#issuecomment-682421124.

**Comment by muffinmad** [comment]
See possible solutions in https://github.com/raxod502/selectrum/issues/169#issuecomment-682421124 thread.
