### ISSUE TITLE
Strange behavior with keybindings

### ISSUE THREAD

**Issue by gcv** [muffinmad/emacs-mini-frame#18]
I use the following piece of code to avoid killing Emacs accidentally:

```emacs-lisp
(global-set-key
 (kbd "C-x C-c")
 (lambda ()
   (interactive)
   (if (not (y-or-n-p "Are you sure you want to exit Emacs? "))
       (message "Canceled exit")
     (save-buffers-kill-emacs))))
```

It normally works, but with mini-frame-mode turned on, it errors out: `Wrong type argument: symbolp, ...`.

**Comment by muffinmad** [comment]
Thanks! Should be fixed now.

As a side note: take a look at `confirm-kill-emacs` variable. E.g.:

```elisp
(setq confirm-kill-emacs 'yes-or-no-p)
```

**Comment by gcv** [comment]
Looks good! Thanks for the quick fix.

(For the record, I actually have a more complex pre-exit procedure than `confirm-kill-emacs` supports: https://github.com/gcv/dotfiles/blob/0a49f69/emacs/init.el#L87-L98.)

**Comment by muffinmad** [comment]
> I actually have a more complex pre-exit procedure than `confirm-kill-emacs` supports

Oh, I see. But that procedure will not be called in case exiting by closing last Emacs frame. `kill-emacs-query-functions` may be useful here. But that is your Emacs after all :)

**Comment by gcv** [comment]
You're right. It was only a matter of time until I did that by accident. 🤦‍♂️

Thank you! My configuration has now been improved.
