### ISSUE TITLE
keys are not being captured while Emacs is busy

### ISSUE THREAD

**Issue by FelipeLema** [muffinmad/emacs-mini-frame#23]
I have the following use case:

I'm using [global-tags](https://melpa.org/#/global-tags) for navigating a project. So sometimes I do ~~`(project-files)`~~ `(project-find-file)` to quickly jump to a certain file in the source code.

So what global-tags does underneath is run a shell command command, get the output, split into a list of lines and last select one of the lines. I'm using tramp (and also not doing an Ivy async process) so it takes a second or two to `ivy` to display.

During that time, Emacs is blocking, but still accepting input. So what I normally due is to start typing _before_ `ivy` displays (because I kinda know beforehand where I'm going to).

And here's the difference: `mini-frame` will queue the input but (incorrectly) forward that input to the last buffer that was focused and *not* to the mini-frame.

Can the input be forcefully captured and redirected to the mini-frame while Emacs is blocking?

PS= great package you did here... can't thank you enough

**Comment by muffinmad** [comment]
> I'm using [global-tags](https://melpa.org/#/global-tags) for navigating a project. So sometimes I do `(project-files)` to quickly jump to a certain file in the source code.

Did you mean `project-find-file`?

> Can the input be forcefully captured and redirected to the mini-frame while Emacs is blocking?

It must be some low-level queued input handle mechanism. E.g. evaluate following code in `emacs -Q`:

```lisp
(progn
  (call-process "sleep" nil nil nil "5")
  (switch-to-buffer (get-buffer-create "*test*")))
```

All the input typed during those 5 seconds goes to the `*test*` buffer.

Now replace `switch-to-buffer` with `switch-to-buffer-other-frame`.

All the input goes to the `*scratch*` buffer, i.e. "old" frame.

I think digging into Emacs source code can lead us to some bug or comments about such behavior. Let this be our homework.

The possible solution is to create `mini-frame` before the long running process will be called. Please take a look at the `mini-frame-advice-functions` and try to add `project-find-file-in` to that list.

> PS= great package you did here... can't thank you enough

Thanks! Glad you liked it!

**Comment by FelipeLema** [comment]
it seems like advising a `project-find-file` (and the like) solves this. Thank you for your help.

**Comment by muffinmad** [comment]
You are welcome.

But please advise a function which as close to reading user input as possible.

The `project-find-file` function uses `thing-at-point` to provide default value. Advising `project-find-file` will create new frame before `thing-at-point` will be called leading to `thing-at-point` return nothing. That's why I propose to advise the `project-find-file-in` function, which is called after `thing-at-point`.
