### ISSUE TITLE
Emacs slowdowns sometimes cause hidden mini frame to appear

### ISSUE THREAD

**Issue by gcv** [muffinmad/emacs-mini-frame#26]
This is tricky to reproduce, and may be related to something in the [emacs-mac port](https://bitbucket.org/mituharu/emacs-mac). When a mini-frame exists but is not visible, then sometimes, when the main Emacs thread slows down, the mini-frame appears, but not in the location where it's supposed to be. For example, when `magit-status` takes a while, the mini-frame might pop up. I've also seen it happen when outline-minor-mode churns through a particularly slow outline-regexp. I can't make it happen with something straightforward like `(sleep-for 5)`, unfortunately.

Given the strangeness of this bug, I'm just opening this ticket in case this is a known problem or someone sees something like it.

**EDIT:** After this happens, Cmd-` (which does OS-level frame switching on the Mac) starts to pick up the mini-frame and allows switching to it. Normally this does not happen. After any command forces the mini frame to render normally, its correct behavior resumes.

**Comment by muffinmad** [comment]
Once mini-frame is hidden, it detached from its parent frame and became normal frame (https://github.com/muffinmad/emacs-mini-frame/commit/7136687e7de2a769185f8d8e0a59257576376692). I'm not sure what makes hidden frames visible in your configuration.

To solve your issue you may try to customize the newly added `mini-frame-detach-on-hide` option. Setting it to `nil` will make mini-frame remains the child frame and we can see if the issue will happen again.

**Comment by gcv** [comment]
Thanks! I just installed your update, set the new option, and will report back.

**Comment by gcv** [comment]
Well, I haven't seen this problem in a few days. Let's call this done. I'll reopen the ticket if I see it again. Thanks again!
