### ISSUE TITLE
debian emacs 27 - mini frame doesnt show initial candidates

### ISSUE THREAD

**Issue by rileyrg** [muffinmad/emacs-mini-frame#27]
miniframe doesnt  show anything until I type something.  Using selectrum if that makes any difference, eg here I open magit and type b l to check out a local branch. Nothing is listed until I type a letter then it works.

![Bildschirmfoto vom 2021-01-06 23-35-28](https://user-images.githubusercontent.com/362891/103826832-eb10a900-5077-11eb-9755-67575ee995dd.png)

Standard use-package

```
      (use-package mini-frame
        :config
        (setq x-gtk-resize-child-frames 'resize-mode)
        (mini-frame-mode))

```

Selectrum

```
       (use-package selectrum
         :config
         (use-package selectrum-prescient
           :config
           (selectrum-mode +1)
           (use-package sudo-edit)
           ;;(global-set-key (kbd "M-r") #'selectrum-repeat)
           :bind
           ("<f4>" . 'find-file)))

```

full [init.el](https://github.com/rileyrg/Emacs-Customisations/blob/master/init.el)

**Comment by muffinmad** [comment]
Maybe related to https://github.com/raxod502/selectrum/issues/169

Does `(setq x-gtk-resize-child-frames 'resize-mode)` helps?

**Comment by rileyrg** [comment]
Unfortunate not. I use i3 and emacs-lucid btw.  Unfortunately I wont be
able to do much with this next days.

**Comment by muffinmad** [comment]
Try advice from https://github.com/raxod502/selectrum/issues/169#issuecomment-712957936

Are you using Emacs 27.1? [Bug#44080](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=44080) is fixed in Emacs 27.2.

It's mentioned in [selectrum wiki](https://github.com/raxod502/selectrum/wiki/Additional-Configuration#display-minibuffer-in-a-child-frame-with-mini-frame).

**Comment by rileyrg** [comment]
I missed that. I'll try it out and close if/when it works. Many thanks.

**Comment by rileyrg** [comment]
Covered in selectrum wiki https://github.com/raxod502/selectrum/issues/169#issuecomment-712957936
