### ISSUE TITLE
Window resize error for "execute-extended-command" when using exwm

### ISSUE THREAD

**Issue by n8m4** [muffinmad/emacs-mini-frame#3]
I get "window-resize: Cannot resize the root window of a frame" error if i use "execute-extended-command" func while "exwm-mode" is on. 

Other functions that display minibuffer, like "evil-ex" work fine.

**Comment by muffinmad** [comment]
What Emacs version do you use? No issue for me on Emacs 26.3 with minimal exwm config like
```elisp
(require 'exwm)
(require 'exwm-config)
(exwm-config-default)
```

Can you please also enable debug on error (`M-x toggle-debug-on-error`) and show the backtrace once error is occured?

**Comment by n8m4** [comment]
I found out that this is caused by setting "ivy-fixed-height-minibuffer" to non nil.

**Comment by muffinmad** [comment]
Can confirm. Even without mini-frame mode.

`emacs -Q --eval "(progn (make-frame '((minibuffer . only))) (setq default-frame-alist '((minibuffer . nil))))"`

```
M-x package-initialize
M-x ivy-mode
M-: (setq ivy-fixed-height-minibuffer t)
M-x
```

leads to

```
Debugger entered--Lisp error: (error "Cannot resize the root window of a frame")
  signal(error ("Cannot resize the root window of a frame"))
  error("Cannot resize the root window of a frame")
  window-resize(#<window 6 on  *Minibuf-1*> -26)
  set-window-text-height(nil 10)
  ivy--minibuffer-setup()
```

There are some issues in exwm and ivy about this:
https://github.com/ch11ng/exwm/issues/489
https://github.com/abo-abo/swiper/issues/380

Does setting `ivy-fixed-height-minibuffer` to `nil` is acceptable solution for you?

**Comment by n8m4** [comment]
It would be nice if ivy could show more than 9 candidates with your package. But if there's nothing you can do, i guess i will go back to using ivy-posframe.

**Comment by muffinmad** [comment]
What about `(setq ivy-height 20)`?

**Comment by n8m4** [comment]
It works. Thanks.
