### ISSUE TITLE
File dialog is opened when invoke mini-buffer with configured focus-out-hook

### ISSUE THREAD

**Issue by jsc57x** [muffinmad/emacs-mini-frame#34]
At least in Windows 10 a file save dialog is triggered if the minibuffer is invoked while the following is configured:
`(add-hook 'focus-out-hook 'save-buffer)`
which should save the buffer at focus-lost but it tries to save the mini-buffer. The save dialog could neither be confirmed nur canceled.

**Comment by muffinmad** [comment]
I see this behavior even without `mini-frame-mode` enabled under macOS. Please try under Windows:

1. `emacs -Q`
2. `M-: (add-hook 'focus-out-hook 'save-buffer)`
3. `M-x`
4. Switch to another app

You can use `save-some-buffers` to save only file-visiting buffers. E.g.:

```elisp
(add-hook 'focus-out-hook (lambda () (save-some-buffers t)))
```

**Comment by jsc57x** [comment]
yeah, I can reproduce it with these steps. The only difference is I can quit with Cancel. Thanks nonetheless.
