### ISSUE TITLE
empty minibuffer is shown fullscreen with activated default-frame-alist

### ISSUE THREAD

**Issue by jsc57x** [muffinmad/emacs-mini-frame#35]
OS: Windows 10
I configured my .emacs to open emacs maximised `(add-to-list 'default-frame-alist '(fullscreen . maximized))`.
Everything works fine unless I switch to another program and come back to emacs. An empty minibuffer will be shown fullscreen and I'm not able to close it or emacs.

Using `initial-frame-alist` is a workaround. Until now I don't have to use `default-frame-alist`

**Comment by muffinmad** [comment]
Please try to add the `(fullscreen . nil)` parameter to the `mini-frame-show-parameters` variable by customizing it or 

```elisp
(add-to-list 'mini-frame-show-parameters '(fullscreen . nil))
```

**Comment by jsc57x** [comment]
Thanks, at a first glance this worked fine.
