### ISSUE TITLE
Redirect frame focus

### ISSUE THREAD

**Issue by Stebalien** [muffinmad/emacs-mini-frame#37]
Sometimes, especially when running an interactive command with slow completion results (flyspell, consult-lines, etc.):

1. I'll run the command.
2. I'll start typing _before_ the mini-frame shows up.
3. When the frame shows up, my input focus will not properly switch to the new frame.

I've found this can bey fixed by calling `(redirect-frame-focus selected-frame mini-frame-frame)` right before `(make-frame-visible mini-frame-frame)` in `mini-frame--display`. This also doesn't appear to have any unwanted side effects.

I'm submitting this as a bug report, not a patch, as:

1. I'm not sure why this is happening.
2. Given this fix, I'd _assume_ that the mini-frame would _keep_ focus (making it impossible to interact with the rest of emacs while the mini-frame is in use). However, this is not the case.

**Comment by muffinmad** [comment]
There were similar issue #23 

I think the `redirect-frame-focus` function is the great solution. I'll add it, thanks for the great idea!

**Comment by muffinmad** [comment]
@Stebalien Can you provide some receipt to reproduce this? I've tested the following code with the `selectrum-mode` enabled:

```elisp
(completing-read
 "foo: "
 (letrec ((table
	   (lazy-completion-table
	    table
	    (lambda ()
	      (call-process "sleep" nil nil nil "3")
	      (list "bar1" "bar2" "bar3")))))))
```

All the keys goes to the minibuffer frame.

**Comment by Stebalien** [comment]
Yeah, that didn't do it for me either. My reproduction process is:

1. Open a large org mode file with lots of org source blocks.
2. Run `consult-line`.

Unlike with the command above, there's a delay between running `consult-line` and actually displaying the `mini-frame`. Looking at a profile, it might be due to fontification/display.

**Comment by muffinmad** [comment]
> 1. Open a large org mode file with lots of org source blocks.
> 2. Run `consult-line`.

Thanks, I can reproduce it as well. Not sure about the reason of such behavior, maybe some hook in the `minibuffer-setup-hook`.
I've added `redirect-frame-focus` as you suggested but after `make-frame-visible`. Hope this solves your issue.

**Comment by Stebalien** [comment]
After appears to work just as well. Thanks!
