### ISSUE TITLE
Canceling the mini-buffer causes annoying glash

### ISSUE THREAD

**Issue by jsyjr** [muffinmad/emacs-mini-frame#40]
After solving #39 mini-frame is working quite nicely now.
One annoyance remains.  If, rather than complete some
action, I cancel (C-g) out of the mini-buffer, I see white
flash, corresponding to the mini-buffer line.
![Peek 2021-04-04 13-14](https://user-images.githubusercontent.com/1302939/113517645-4e16bc80-954f-11eb-85ce-1890e829a17d.gif)

Is there anyway to eliminate that flash?

**Comment by muffinmad** [comment]
Can you please check this in `emacs -Q`?

I've checked it with this minimal setup and didn't notice any flashing:

```elisp
(setq mini-frame-standalone t)
(setq mini-frame-show-parameters (lambda ()
				   (let ((sf (selected-frame)))
                                     `((left . ,(frame-parameter sf 'left))
                                       (width . ,(frame-parameter sf 'width))
                                       (top   . ,(frame-parameter sf 'top))))))
```

This is may be GTK version specific.

**Comment by jsyjr** [comment]
Solved it.  I forgot about visible-bell, in part because it is rendered more attractively when the minibuffer does not disappear before the flash.

This [stackoverflow thread ](https://stackoverflow.com/questions/11679700/emacs-disable-beep-when-trying-to-move-beyond-the-end-of-the-document)provided inspiration for a solution.  I had to add `abort-minibuffers` to the list of suppressed commands.
