### ISSUE TITLE
How to add custom colors?

### ISSUE THREAD

**Issue by basicfunc** [muffinmad/emacs-mini-frame#49]
![image](https://user-images.githubusercontent.com/84739019/126873430-02fe91ee-e3d9-4aff-b51e-75676ed8cd23.png)

Hey Dev!!
As you can see above, due to theme, default options are not highlighted.
I tried to dig a bit but due to lack of knowledge, I couldn't able to find any solution for that.
I only able to found that Mini Frame get colors from mini-frame-get-background-color function.

Is there any workaround or option to change background, foreground and highlighted option color?

**Comment by muffinmad** [comment]
Hi @basicfunc 

It depends on completion framework you are using. Does it looks different with `mini-frame` mode turned off?

**Comment by basicfunc** [comment]
Hey,
I'm using selectrum and yes it does look different when ` mini-frame ` turned off!
![image](https://user-images.githubusercontent.com/84739019/127152548-42fc5b2a-3ad2-4fae-a3cb-d1c69fb97080.png)
As you can see in the above screenshot vterm is highlighted.

**Comment by muffinmad** [comment]
I see.

Set the `background-color` parameter in the `mini-frame-show-parameters` variable or decrease the value of the `mini-frame-color-shift-step` variable.

**Comment by basicfunc** [comment]
> I see.
> 
> Set the `background-color` parameter in the `mini-frame-show-parameters` variable or decrease the value of the `mini-frame-color-shift-step` variable.

Thanks, that worked
