### ISSUE TITLE
Issues when quitting completion

### ISSUE THREAD

**Issue by untoreh** [muffinmad/emacs-mini-frame#51]
I am using wslg with emacs-pgtk, when I try to close the miniframe, it is moved down, and is still visible, and it appears as a window in itself, you can cycle ALT-TAB to it from windows; the window is only present after I quit the completion (if I try to ALT-TAB while reading a completion, the minibuffer frame/window is not present, can't be ALT-TABbed).
![miniframe](https://user-images.githubusercontent.com/2363212/131324953-3c92f3e2-8a11-4540-9e7f-5d403fd50f9c.gif)

**Comment by muffinmad** [comment]
On completion quit the mini-frame become hidden and by default detached from parent frame. Not sure what make the mini-frame visible - pgtk or wslg or both.
Try to set the `mini-frame-detach-on-hide` variable to `nil`

**Comment by untoreh** [comment]
that solves it, the downside doesn't bother me since I rarely reopen frames :)
