### ISSUE TITLE
Visual line mode

### ISSUE THREAD

**Issue by arjunkathuria** [muffinmad/emacs-mini-frame#56]
hi,

long lines (like pathnames) need to be scrolled to the end on my half width minibuffer, to get the full idea, i'd like to enable visual-line-mode for just the mini-buffer.

any way i can do that? thanks.

**Comment by arjunkathuria** [comment]
i tried doing

```elisp
(mini-frame-show-parameters (lambda () (visual-line-mode 1) '((left . 0.5) (top . 0.25) (width . 0.55))))
```

with no success though : /

**Comment by muffinmad** [comment]
Hi. I think it's something related to mini-buffer size calculation. If mini-frame width is set to frame width (`1.0`), it is resized properly.

I have no solution for this at the moment.

**Comment by arjunkathuria** [comment]
bummer.

ah well, thanks for the reply.

guess i'll go back to occasionally using it.

**Comment by muffinmad** [comment]
Solved in https://github.com/muffinmad/emacs-mini-frame/pull/61
