### ISSUE TITLE
What is your theme?

### ISSUE THREAD

**Issue by LionyxML** [muffinmad/emacs-mini-frame#58]
Hello there!

I have this setup with `emacs-mini-frame` and `ivy-mode`, but I can barely see what is selected.

![image](https://user-images.githubusercontent.com/16169950/158908217-093166eb-4910-4f19-ab40-70fb62714f86.png)

![image](https://user-images.githubusercontent.com/16169950/158908240-d91a4747-faa0-4a81-ace6-e06f2b992bed.png)

I had no success with any dark themes :( , so I'd like to know what theme you are using on the README. :)

Thanks!

**Comment by muffinmad** [comment]
Hi!

There is the `mini-frame-color-shift-step` option which specify the step by which background color of the mini frame will be "shifted". Try to set it to lower value, like 10.

As for my theme, it is the custom one base on Emacs default. There are not so many tweaks, just background and foreground and few other colors:
```elisp
(deftheme mad
  "My theme")

(custom-theme-set-faces
 'mad

 '(default ((t :foreground "#cccccc" :background "#0f0f23")))
 '(fringe ((t :background unspecified :foreground "gray29")))
 '(vertical-border ((t :background "#2d2d2d" :foreground "#2d2d2d")))

 '(highlight ((t :background "dark slate gray")))
 '(hl-line ((t :background "#222222")))

 '(error ((t :foreground "indianred1")))
 '(warning ((t :foreground "yellow3")))

 '(mode-line ((t :inherit default :foreground "gray83" :background "#252539")))
 '(mode-line-inactive ((t :inherit mode-line :weight light :foreground "gray43")))
 '(mode-line-highlight ((t :background "#353549")))

 '(header-line ((t :foreground "gray83" :background "#202034")))

 '(font-lock-doc-face ((t :foreground "gray49")))
 '(font-lock-comment-face ((t :foreground "gray39")))
 '(font-lock-constant-face ((t :foreground "thistle1")))
 '(font-lock-keyword-face ((t :foreground "#efefef")))

 '(show-paren-match ((t :background "darkslategray")))
 '(show-paren-mismatch ((t :background "indianred3")))

 '(js2-error ((t :foreground "indianred1")))

 '(org-block ((t :background "#151525" :extend t)))
 '(org-block-begin-line ((t :inherit org-meta-line :background "#181828" :extend t)))

 '(diff-refine-added ((t :background "#227722")))
 '(diff-refine-changed ((t :background "#aa7722")))

 '(which-func ((t :foreground "LightBlue4")))

 '(eglot-highlight-symbol-face ((t :underline "dark slate gray")))
 '(eglot-mode-line ((t (:inherit font-lock-comment-face)))))

(provide-theme 'mad)
;;; mad-theme.el ends here
```

**Comment by LionyxML** [comment]
Awesome! Thanks a lot! And you were fast! :) 

I actually had to change `mini-frame-color-shift-step` to something like 60.
![Captura de Tela 2022-03-18 às 08 45 09](https://user-images.githubusercontent.com/16169950/158997413-deae6d00-8470-477b-8e66-0ffc1188ea73.png)

Adding a colored bar or appending a ">" function to the left of what is under selection is currently possible?

Thanks again!

**Comment by muffinmad** [comment]
That option has existed for a prettry long time. Maybe the README should contain info about available options for better discoverability.

As for `>` under selection, it's depends on completion framework you're using. mini-frame just moves the minibuffer to separate frame and do not interfere with the text inside the minibuffer. So it is the `ivy-mode` who should mark the selected item with additional symbol.

**Comment by muffinmad** [comment]
Actually `ivy` has such option :) Take a look at `ivy-format-functions-alist`. Just set it to `((t . ivy-format-function-arrow))` and voila!
<img width="576" src="https://user-images.githubusercontent.com/2702727/159000489-5b225d4a-9d57-4648-a2bf-f3f6afe3d23d.png">

**Comment by LionyxML** [comment]
Thanks man!

Made my life a lot easier :D 

I actually went for arrow + all line selection option:

![image](https://user-images.githubusercontent.com/16169950/159147638-6a6f323e-3ce4-46ba-acad-76e0c0630413.png)
