### ISSUE TITLE
Cannot set mini-frame to transparent

### ISSUE THREAD

**Issue by andreyyao** [muffinmad/emacs-mini-frame#65]
Emacs version: GNU Emacs 28.1
OS: 5.16.18-1-MANJARO
Desktop: KDE Plasma 5.24.6

Thanks for writing this package. I have been perpetually annoyed by my modeline jumping around when mini buffer resizes. It's not an issue anymore thanks to mini-frame.

However, I cannot set the transparency of the mini-frame when it is child frame through the `alpha` frame parameter. But as a standalone frame, it does show up as transparent. My compositor is KDE's kwin, and transparency definitely works in general.

Value of `mini-frame-show-parameters`
```
'((left . 0.5)
  (top . 0.0)
  (width . 1.0)
  (height . 1)
  (alpha . 50))
```

No standalone (child frame):
![Screenshot_20220803_152645](https://user-images.githubusercontent.com/96220436/182706216-c7c343f9-c4e9-4ffb-af3d-ccedb0877a81.png)

Standalone (transparency working):
![Screenshot_20220803_153217](https://user-images.githubusercontent.com/96220436/182706249-4e0a59e0-2fee-4b2f-95cd-b24802c19350.png)

**Comment by muffinmad** [comment]
Hi,

I'm glad you find this package usefull.

Child frame transparency works as expected for me on macOS.

Tested this snippet under Gnome Shell:
```elisp
(make-frame `((parent-frame . ,(selected-frame))
              (width . 0.5)
              (height . 0.5)
              (alpha . 50)))
```
And newly created child frame is not transparent.

Maybe it is specific to OS.

**Comment by andreyyao** [comment]
Thanks for the reply. I think I phrased the question poorly, but the expected behavior for me was for the child frame to be transparent. Do you know if this is possible?

**Comment by muffinmad** [comment]
The point is the same code for creating transparent child frame works different on different platforms. It works as expected on NS port and does not work on GTK port. I'm affraid there nothing we can do about it on `mini-frame` side and this issue must be solved in Emacs itself.

**Comment by andreyyao** [comment]
I see. I will just tweak other options to make the mini-frame look nice. Thanks!
