### ISSUE TITLE
Mini frame min width?

### ISSUE THREAD

**Issue by thomasheartman** [muffinmad/emacs-mini-frame#66]
Is there a way to specify a minimum width for the mini frame? For instance, when Emacs occupies my full screen, I don't want the mini-frame to take up more than 50% of the width, but when the emacs frame is narrowed, I'd like the mini frame to take up at least n pixels.

I feel like I've seen a way to do this before, but I couldn't find anything while looking now.

Thanks! 🙏🏼

**Comment by muffinmad** [comment]
I think it possible with two options:
1. Add the `min-width` parameter to the `mini-frame-show-parameters` variable. See [the docs](https://www.gnu.org/software/emacs/manual/html_node/elisp/Size-Parameters.html) for more info on frame parameters
2. Set the `mini-frame-show-parameters` variable to custom a function that will calculate and return required frame parameters.

**Comment by thomasheartman** [comment]
Super! That did just what I wanted it to 😄  

For reference, here's the function I ended up with: 

```elisp
(defun heartman/mini-frame-show-params ()
  (let* ((min-desired-width 125) 
	 (min-width (min (frame-width) min-desired-width)))
    `((top . 15)
      (width . 0.5)
      (left . 0.5)
      (alpha . 95)
      (min-width . ,min-width))))
```

In short, I say that I always want the frame to be at least 125 chars wide _unless_ the frame is smaller. In that case, set it to be as wide as the frame. The other params are just my personal preference. 

Thanks! 🙏🏼
