### ISSUE TITLE
Conflict with vertico-multiform

### ISSUE THREAD

**Issue by yusi1** [muffinmad/emacs-mini-frame#68]
I use vertico-multiform to change the style that completion candidates are shown in, for example `vertico-multiform-flat` changes the completions to a "flat" list that shows 1 candidate as you type, you can also automatically change the completion candidate style for different commands.

So I changed what M-x (execute-extended-command) looks like with that "flat" style, but I get an error with mini-frame, which blocks `execute-extended-command` from running, therefore I can't M-x:
`
Error in minibuffer-exit-hook (vertico-multiform--exit): (error "Cannot resize the root window of a frame")
`

So there is some conflict going on between vertico-multiform-flat and mini-frame, this error doesn't occur with `find-file` and `consult-buffer` since I don't use vertico-multiform on them to change what completion candidates look like.

Idk about the internals of Vertico or mini-frame etc.., so I won't be able to make a PR, bcs I am a beginner at Emacs, but for the meantime I will comment the vertico-multiform stuff out in my config so I can use M-x. I'll leave this issue here anyway.

**Comment by muffinmad** [comment]
I can reproduce it without `mini-frame`. I've created issue in vertico repo, see https://github.com/minad/vertico/issues/279

**Comment by muffinmad** [comment]
Should be fixed in vertico.

**Comment by yusi1** [comment]
> Should be fixed in vertico.

Nice, thanks alot!
