### ISSUE TITLE
Conflict with consult-imenu

### ISSUE THREAD

**Issue by yusi1** [muffinmad/emacs-mini-frame#69]
When I have `mini-frame-mode` enabled and call `consult-imenu`, this error occurs:
`redisplay--pre-redisplay-functions: (error "Cannot resize the root window of a frame")`

Also, one thing to mention is that `consult-imenu` also creates it's own buffer, but the menu is available in both the mini-frame and the buffer that `consult-imenu` creates.

Would there be any way to disable `mini-frame-mode` before `consult-imenu` creates its own buffer?

This issue is not reproducible with standard `imenu`.

**Comment by yusi1** [comment]
I will link a video, two seconds.

**Comment by yusi1** [comment]
https://user-images.githubusercontent.com/82241382/190871750-0d2d5183-bb73-4aba-89ce-72f318899c2a.mp4

**Comment by yusi1** [comment]
Issue doesn't occur with normal imenu.

https://user-images.githubusercontent.com/82241382/190871788-c0e8c1af-531b-4ecd-bbf2-9664a4f0139e.mp4

**Comment by muffinmad** [comment]
I'm not familiar with `consult`, would be greate if you can provide some steps for reproduce this issue starting from `emacs -Q`.

Also you can turn off `mini-frame` for `consult-imenu` by adding `consult-imenu` to `mini-frame-ignore-commands`.

**Comment by yusi1** [comment]
> I'm not familiar with `consult`, would be greate if you can provide some steps for reproduce this issue starting from `emacs -Q`.

Here's a minimal config, but it seems the error didn't occur when I tried `emacs -Q` with this minimal config.

``
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
(package-initialize)

(package-install 'mini-frame)
(package-install 'consult)

(require 'mini-frame)
(mini-frame-mode)

(require 'consult)
``

> Also you can turn off `mini-frame` for `consult-imenu` by adding `consult-imenu` to `mini-frame-ignore-commands`.

Thank you, this is all I needed, AFAIK I don't think the issue is with either `consult` or `mini-frame`, because when I tried `emacs -Q` with a minimal config, the error didn't occur.

**Comment by yusi1** [comment]
I think the issue is with my configuration maybe.

**Comment by yusi1** [comment]
> Also you can turn off `mini-frame` for `consult-imenu` by adding `consult-imenu` to `mini-frame-ignore-commands`.

This fix is fine for me and has solved the issue.
