### ISSUE TITLE
emacs 29 wrong-number-of-arguments #<subr string-match> 4

### ISSUE THREAD

**Issue by Inc0n** [muffinmad/emacs-mini-frame#72]
I am having this error on just `M-x`.
```
Debugger entered--Lisp error: (wrong-number-of-arguments #<subr string-match> 4)
  string-match("edebug-eval-expression" "execute-extended-command" nil t)
  mini-frame-read-from-minibuffer(#<subr read-from-minibuffer> "M-x " nil keymap nil extended-command-history nil nil)
```

**Comment by muffinmad** [comment]
Does it happens it `emacs -Q`? Just build recent Emacs 29 versio (commit 58b8ed8b55cd3c864823c6d2fbfdd12bcfe43247) and can't reproduce this issue.

**Comment by Inc0n** [comment]
Ahh, it doesn't actually. No it does not happen with `emacs -Q`.

Weird, only after with my full config loaded. I do not think I will investigate this too much, since I do have a work around shown in PR https://github.com/muffinmad/emacs-mini-frame/pull/74.

But thanks for the instructions! I should apply the `emacs -Q` test in future cases.
