### ISSUE TITLE
mini-frame will have a scroll bar if scroll-bar-mode is on

### ISSUE THREAD

**Issue by Inc0n** [muffinmad/emacs-mini-frame#73]
mini-frame will also have a scroll bar if `scroll-bar-mode` is on.
In my particular case, I had it on `right`. And there is a visible white stripe on its right.

Once `scroll-bar-mode` is turned off, mini-frame will not display the white stripe (or scroll bar).

I think in most case, it would be undersirable to have mini-frame also respect scroll-bar-mode (slightly visually unpleasant)

What do you think?

**Comment by muffinmad** [comment]
Or even better: add `vertical-scroll-bars . nil` to `mini-frame-show-parameters`. Scroll bars can be actually turned off for individual frames using this parameter. That is what `toggle-scroll-bar` do internally.

**Comment by Inc0n** [comment]
> Or even better: add `vertical-scroll-bars . nil` to `mini-frame-show-parameters`. Scroll bars can be actually turned off for individual frames using this parameter. That is what `toggle-scroll-bar` do internally.


Yes that works. Just pure bliss now, the visual eye candy, thank you very much!
