### ISSUE TITLE
Disable mini-frame for all one-line minibufers

### ISSUE THREAD

**Issue by zhenhua-wang** [muffinmad/emacs-mini-frame#75]
Hi, is it possible to disable mini-frame for all one-line minibufers? (for example, y-or-n-p). I know that we can add `y-or-n-p` to `mini-frame-ignore-functions`. However, I would like to have this behavior for all future one-line minibuffers. Thank you.

**Comment by muffinmad** [comment]
Hi!

Take a look at `mini-frame-advice-functions` option. Set it to `completing-read` and mini-buffer will be used only when reading from minibuffer with completions.
