### ISSUE TITLE
isearch support?

### ISSUE THREAD

**Issue by katspaugh** [muffinmad/emacs-mini-frame#82]
I saw the mini-frame was disabled for isearch-mode in [this commit](https://github.com/muffinmad/emacs-mini-frame/commit/b90647b946c82627c6fe22731730f9e9060d5ced).

Would it be possible to bring it back in and fix #48 in a cleaner way? Perhaps it could be added to the ignored commands instead, so that it's customizable?

I tried reverting that commit locally but somehow isearch is still not popping up a mini-frame. Looking at the isearch code, it seems to be using the `read-from-minibuffer` function, so it should theoretically work?

**Comment by muffinmad** [comment]
isearch is using `read-from-minibuffer` on `isearch-edit-string`. Press `M-e` after `C-s` and you should see mini-frame.

**Comment by katspaugh** [comment]
I see, thanks a lot. Awesome plugin!
