### ISSUE TITLE
kill-buffer prompt gets truncated oddly

### ISSUE THREAD

**Issue by n-hebert** [muffinmad/emacs-mini-frame#86]
# Install & Config
```
  (use-package mini-frame
    :config
    (setq mini-frame-resize nil)
    (mini-frame-mode +1)
    (custom-set-variables
      '(mini-frame-show-parameters
         '((top . 0.3)
           (width . 0.5)
           (left . 0.5)
           (height . 10)))))
```
# Steps to reproduce

1. Open a buffer
2. Type some text
3. C-x k and select this buffer

## Expected Result
It shows the prompt to the user: "Buffer $BUFFER modified; kill anyway?" etc etc

## Actual Result
It says `yway? (yes/no/save and then kill)` and it's a little confusing. A user can't really answer.

![image](https://github.com/muffinmad/emacs-mini-frame/assets/68243838/351f74a4-4551-4d6a-bf84-803f43ad6ab0)

**Comment by muffinmad** [comment]
What is completion package used in screenshot? How the prompt looks like with mini-frame mode turned off and with Emacs frame smaller width?

**Comment by n-hebert** [comment]
That would be [selectrum](https://github.com/radian-software/selectrum), and here it is without mini-frame mode:
![image](https://github.com/muffinmad/emacs-mini-frame/assets/68243838/d912d14d-7b30-4609-a7d9-8081c7553db3)

Good thinking! 
So it seems to be related to selectrum and the window width, not strictly mini-frame :open_mouth: 

Any tips? I can go file an issue over there, if that sounds like the best plan of action.
Cheers

**Comment by n-hebert** [comment]
p.s. For now increasing the width of the mini-frame is indeed a work-around for this particular prompt. A more general solution would require a code change, of course, on emacs itself, mini-frame, or selectrum.

**Comment by muffinmad** [comment]
I think it should be handled in selectrum itself. Emacs shows the full prompt.
<img width="301" alt="Screenshot 2024-03-17 at 10 07 06" src="https://github.com/muffinmad/emacs-mini-frame/assets/2702727/02aa0e28-acc6-49bc-b3d4-30a32b9b26a2">

**Comment by n-hebert** [comment]
Sounds good, I'll file something over there. Cheers!
